"""Stable error codes and the typed exception that crosses API boundaries."""

from __future__ import annotations

import inspect
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from octop.i18n import error_message as i18n_error_message
from octop.infra.utils.locale import Locale, normalize_locale

#: The names ``error_message`` already owns. A ``details`` key with one of these
#: names must not be forwarded as an interpolation kwarg (see
#: ``OctopError.interpolation_kwargs``); derived from the signature so it cannot go
#: stale.
_ERROR_MESSAGE_PARAMS = frozenset(inspect.signature(i18n_error_message).parameters)


class ErrorCode(StrEnum):
    AUTH_FAILED = "AUTH_FAILED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    SETUP_REQUIRED = "SETUP_REQUIRED"
    DATABASE_NOT_EMPTY = "DATABASE_NOT_EMPTY"
    BACKUP_DRIVER_MISMATCH = "BACKUP_DRIVER_MISMATCH"
    BACKUP_SCHEMA_INCOMPATIBLE = "BACKUP_SCHEMA_INCOMPATIBLE"
    BACKUP_IN_PROGRESS = "BACKUP_IN_PROGRESS"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    USER_DISABLED = "USER_DISABLED"
    LOGIN_LOCKED = "LOGIN_LOCKED"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    EMAIL_INVALID = "EMAIL_INVALID"
    PASSWORD_SAME_AS_OLD = "PASSWORD_SAME_AS_OLD"
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"
    SETUP_PASSWORD_WRONG = "SETUP_PASSWORD_WRONG"
    SETUP_RATE_LIMITED = "SETUP_RATE_LIMITED"
    SETUP_TOKEN_INVALID = "SETUP_TOKEN_INVALID"
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_NOT_RUNNING = "AGENT_NOT_RUNNING"
    AGENT_FAILED = "AGENT_FAILED"
    AGENT_BUSY = "AGENT_BUSY"
    AGENT_NAME_TAKEN = "AGENT_NAME_TAKEN"
    AGENT_ID_INVALID = "AGENT_ID_INVALID"
    AGENT_ID_TAKEN = "AGENT_ID_TAKEN"
    PROVIDER_NAME_TAKEN = "PROVIDER_NAME_TAKEN"
    PROVIDER_NOT_VISIBLE = "PROVIDER_NOT_VISIBLE"
    PROVIDER_REFERENCED = "PROVIDER_REFERENCED"
    PROVIDER_LOCAL_PROTECTED = "PROVIDER_LOCAL_PROTECTED"
    CODEX_OAUTH_START_FAILED = "CODEX_OAUTH_START_FAILED"
    STORAGE_BACKEND_NAME_TAKEN = "STORAGE_BACKEND_NAME_TAKEN"
    STORAGE_BACKEND_REFERENCED = "STORAGE_BACKEND_REFERENCED"
    STORAGE_BACKEND_DEPS_FAILED = "STORAGE_BACKEND_DEPS_FAILED"
    CHANNEL_KIND_UNSUPPORTED = "CHANNEL_KIND_UNSUPPORTED"
    CHANNEL_INVALID_CREDENTIALS = "CHANNEL_INVALID_CREDENTIALS"
    CHANNEL_NAME_TAKEN = "CHANNEL_NAME_TAKEN"
    CONNECTOR_NOT_FOUND = "CONNECTOR_NOT_FOUND"
    CONNECTOR_NAME_TAKEN = "CONNECTOR_NAME_TAKEN"
    CONNECTOR_INVALID_CREDENTIALS = "CONNECTOR_INVALID_CREDENTIALS"
    CONNECTOR_OAUTH_HTTPS_REQUIRED = "CONNECTOR_OAUTH_HTTPS_REQUIRED"
    CONNECTOR_MCP_URL_INVALID = "CONNECTOR_MCP_URL_INVALID"
    CONNECTOR_MCP_HTTPS_REQUIRED = "CONNECTOR_MCP_HTTPS_REQUIRED"
    CONNECTOR_KIND_UNSUPPORTED = "CONNECTOR_KIND_UNSUPPORTED"
    CONNECTOR_NOT_BOUND = "CONNECTOR_NOT_BOUND"
    CONNECTOR_ALREADY_BOUND = "CONNECTOR_ALREADY_BOUND"
    CONNECTOR_MCP_LOAD_FAILED = "CONNECTOR_MCP_LOAD_FAILED"
    BRIDGE_NOT_FOUND = "BRIDGE_NOT_FOUND"
    BRIDGE_AUTH_FAILED = "BRIDGE_AUTH_FAILED"
    BRIDGE_PEER_UNREACHABLE = "BRIDGE_PEER_UNREACHABLE"
    BRIDGE_NOT_CONNECTED = "BRIDGE_NOT_CONNECTED"
    BRIDGE_TUNNEL_FAILED = "BRIDGE_TUNNEL_FAILED"
    BRIDGE_REMOTE_UNSUPPORTED = "BRIDGE_REMOTE_UNSUPPORTED"
    BRIDGE_DISPLAY_NAME_TAKEN = "BRIDGE_DISPLAY_NAME_TAKEN"
    BRIDGE_INBOUND_PASSIVE = "BRIDGE_INBOUND_PASSIVE"
    CRON_TRIGGER_INVALID = "CRON_TRIGGER_INVALID"
    SLASH_UNKNOWN = "SLASH_UNKNOWN"
    SLASH_BAD_ARGS = "SLASH_BAD_ARGS"
    ATTACHMENT_UNSUPPORTED_TYPE = "ATTACHMENT_UNSUPPORTED_TYPE"
    ATTACHMENT_TOO_LARGE = "ATTACHMENT_TOO_LARGE"
    VOICE_BROWSER_ONLY = "VOICE_BROWSER_ONLY"
    VOICE_KIND_UNSUPPORTED = "VOICE_KIND_UNSUPPORTED"
    VOICE_CAPABILITY_MISMATCH = "VOICE_CAPABILITY_MISMATCH"
    VOICE_PROVIDER_DISABLED = "VOICE_PROVIDER_DISABLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    TLS_NOT_ELIGIBLE = "TLS_NOT_ELIGIBLE"
    TLS_ISSUE_IN_PROGRESS = "TLS_ISSUE_IN_PROGRESS"
    TLS_DOMAIN_MISMATCH = "TLS_DOMAIN_MISMATCH"
    WORKSPACE_OP_UNSUPPORTED = "WORKSPACE_OP_UNSUPPORTED"
    SKILL_IMPORT_UNSUPPORTED_URL = "SKILL_IMPORT_UNSUPPORTED_URL"
    SKILL_IMPORT_FAILED = "SKILL_IMPORT_FAILED"
    SKILL_ALREADY_EXISTS = "SKILL_ALREADY_EXISTS"
    SKILL_PACKAGE_NOT_FOUND = "SKILL_PACKAGE_NOT_FOUND"
    SKILL_PACKAGE_NAME_TAKEN = "SKILL_PACKAGE_NAME_TAKEN"
    SKILL_PACKAGE_BACKEND_UNSUPPORTED = "SKILL_PACKAGE_BACKEND_UNSUPPORTED"
    ACP_BACKEND_UNSUPPORTED = "ACP_BACKEND_UNSUPPORTED"
    PUBLISHED_EXPERT_SLUG_TAKEN = "PUBLISHED_EXPERT_SLUG_TAKEN"
    PUBLISHED_EXPERT_ALREADY_EXISTS = "PUBLISHED_EXPERT_ALREADY_EXISTS"
    OIDC_BAD_REQUEST = "OIDC_BAD_REQUEST"
    SSO_IDENTITY_TAKEN = "SSO_IDENTITY_TAKEN"
    SSO_UNBIND_REQUIRES_PASSWORD = "SSO_UNBIND_REQUIRES_PASSWORD"
    EXPERT_MARKET_FAILED = "EXPERT_MARKET_FAILED"
    SKILLHUB_SSL_FAILED = "SKILLHUB_SSL_FAILED"
    DESKTOP_SESSION_LIMIT = "DESKTOP_SESSION_LIMIT"
    DESKTOP_CAPTURE_FAILED = "DESKTOP_CAPTURE_FAILED"
    PLUGIN_INVALID_ARCHIVE = "PLUGIN_INVALID_ARCHIVE"
    PLUGIN_INSTALL_FAILED = "PLUGIN_INSTALL_FAILED"
    PLUGIN_ALREADY_EXISTS = "PLUGIN_ALREADY_EXISTS"
    KNOWLEDGE_FEATURE_DISABLED = "KNOWLEDGE_FEATURE_DISABLED"
    KNOWLEDGE_PREREQUISITES_FAILED = "KNOWLEDGE_PREREQUISITES_FAILED"
    KNOWLEDGE_NOT_FOUND = "KNOWLEDGE_NOT_FOUND"
    KNOWLEDGE_FORBIDDEN = "KNOWLEDGE_FORBIDDEN"
    KNOWLEDGE_DOC_LIMIT = "KNOWLEDGE_DOC_LIMIT"
    KNOWLEDGE_DOC_TOO_LARGE = "KNOWLEDGE_DOC_TOO_LARGE"
    KNOWLEDGE_BASE_LIMIT = "KNOWLEDGE_BASE_LIMIT"
    KNOWLEDGE_UNSUPPORTED_TYPE = "KNOWLEDGE_UNSUPPORTED_TYPE"
    KNOWLEDGE_NAME_TAKEN = "KNOWLEDGE_NAME_TAKEN"
    KNOWLEDGE_NAME_INVALID = "KNOWLEDGE_NAME_INVALID"
    AVATAR_INVALID = "AVATAR_INVALID"
    AVATAR_TOO_LARGE = "AVATAR_TOO_LARGE"
    INVITE_INVALID = "INVITE_INVALID"
    INVITE_ROLE_MISSING = "INVITE_ROLE_MISSING"
    USER_ROLE_IN_USE = "USER_ROLE_IN_USE"
    INVITE_USED = "INVITE_USED"
    INVITE_EXPIRED = "INVITE_EXPIRED"
    INVITE_REVOKED = "INVITE_REVOKED"
    INVITE_RATE_LIMITED = "INVITE_RATE_LIMITED"
    WORKSPACE_ROOT_RESTRICTED = "WORKSPACE_ROOT_RESTRICTED"
    WORKSPACE_ROOT_CONTAINER_UNSUPPORTED = "WORKSPACE_ROOT_CONTAINER_UNSUPPORTED"
    TOKEN_QUOTA_EXCEEDED = "TOKEN_QUOTA_EXCEEDED"
    AGENT_QUOTA_EXCEEDED = "AGENT_QUOTA_EXCEEDED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    CAPTCHA_FAILED = "CAPTCHA_FAILED"
    CONFIG_FILE_CORRUPT = "CONFIG_FILE_CORRUPT"
    TEAM_NOT_FOUND = "TEAM_NOT_FOUND"
    TEAM_MEMBERS_TOO_FEW = "TEAM_MEMBERS_TOO_FEW"
    TEAM_MEMBER_INVALID = "TEAM_MEMBER_INVALID"
    TEAM_MEMBER_BUSY = "TEAM_MEMBER_BUSY"
    TEAM_NOT_SHAREABLE = "TEAM_NOT_SHAREABLE"
    # --- expert-team run/pipeline rejection codes (T-15; authority = PLAN.md 拒绝码词表) ---
    # A 组 20：门禁 / API 码
    TEAM_RUN_NOT_FOUND = "TEAM_RUN_NOT_FOUND"
    TEAM_RUN_PHASE_INVALID = "TEAM_RUN_PHASE_INVALID"
    TEAM_PHASE_GATE_FAILED = "TEAM_PHASE_GATE_FAILED"
    TEAM_DECISION_PENDING = "TEAM_DECISION_PENDING"
    TEAM_DECISION_NOT_PENDING = "TEAM_DECISION_NOT_PENDING"
    TEAM_DECISION_OPTION_INVALID = "TEAM_DECISION_OPTION_INVALID"
    TEAM_SPEC_BOUNDARY_EMPTY = "TEAM_SPEC_BOUNDARY_EMPTY"
    TEAM_TASK_DEPS_UNMET = "TEAM_TASK_DEPS_UNMET"
    TEAM_TASK_GRAPH_INVALID = "TEAM_TASK_GRAPH_INVALID"
    TEAM_REWORK_LOOP_LIMIT = "TEAM_REWORK_LOOP_LIMIT"
    TEAM_FINDING_REOPENED = "TEAM_FINDING_REOPENED"
    TEAM_ATTEMPT_STALE = "TEAM_ATTEMPT_STALE"
    TEAM_SCOPE_VIOLATION = "TEAM_SCOPE_VIOLATION"
    TEAM_VERDICT_FINDINGS_REQUIRED = "TEAM_VERDICT_FINDINGS_REQUIRED"
    TEAM_REVIEW_SELF_AUDIT = "TEAM_REVIEW_SELF_AUDIT"
    TEAM_ARTIFACT_STALE = "TEAM_ARTIFACT_STALE"
    TEAM_ARTIFACT_OWNERSHIP_DENIED = "TEAM_ARTIFACT_OWNERSHIP_DENIED"
    TEAM_RUN_MEMBER_LIMIT = "TEAM_RUN_MEMBER_LIMIT"
    TEAM_RUN_TASK_LIMIT = "TEAM_RUN_TASK_LIMIT"
    TEAM_RUN_ROSTER_EMPTY = "TEAM_RUN_ROSTER_EMPTY"
    # --- plan gate (T2; authority = PLAN.md §2.4 拒绝码与状态 — 本批只新增这 2 个) ---
    TEAM_PLAN_DRAFT_INVALID = "TEAM_PLAN_DRAFT_INVALID"
    TEAM_PLAN_DRAFT_MISSING = "TEAM_PLAN_DRAFT_MISSING"
    TEAM_TIER_INVALID = "TEAM_TIER_INVALID"
    # B 组 16：生效边界码（B1–B29）
    TEAM_ROLE_UNKNOWN = "TEAM_ROLE_UNKNOWN"
    TEAM_TIER_DOWNGRADE_FORBIDDEN = "TEAM_TIER_DOWNGRADE_FORBIDDEN"
    TEAM_RUN_CONFLICT = "TEAM_RUN_CONFLICT"
    TEAM_TASK_CLAIM_CONFLICT = "TEAM_TASK_CLAIM_CONFLICT"
    TEAM_PHASE_CONFLICT = "TEAM_PHASE_CONFLICT"
    TEAM_CROSS_RUN_REFERENCE = "TEAM_CROSS_RUN_REFERENCE"
    TEAM_RUN_TERMINAL = "TEAM_RUN_TERMINAL"
    TEAM_TASK_TERMINAL = "TEAM_TASK_TERMINAL"
    TEAM_TASK_STATUS_INVALID = "TEAM_TASK_STATUS_INVALID"
    TEAM_MEMBER_NOT_IN_RUN = "TEAM_MEMBER_NOT_IN_RUN"
    TEAM_ARTIFACT_INVALID = "TEAM_ARTIFACT_INVALID"
    TEAM_ARTIFACT_PATH_INVALID = "TEAM_ARTIFACT_PATH_INVALID"
    TEAM_RUN_GOAL_EMPTY = "TEAM_RUN_GOAL_EMPTY"
    TEAM_RUN_GOAL_TOO_LONG = "TEAM_RUN_GOAL_TOO_LONG"
    TEAM_COMMAND_UNKNOWN = "TEAM_COMMAND_UNKNOWN"
    TEAM_EFFORT_INVALID = "TEAM_EFFORT_INVALID"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_FORBIDDEN = "PROJECT_FORBIDDEN"
    PROJECT_ROLE_FORBIDDEN = "PROJECT_ROLE_FORBIDDEN"
    PROJECT_MEMBER_INVALID = "PROJECT_MEMBER_INVALID"
    PROJECT_STATUS_INVALID = "PROJECT_STATUS_INVALID"
    PROJECT_TASK_NOT_FOUND = "PROJECT_TASK_NOT_FOUND"
    PROJECT_TASK_THREAD_NOT_FOUND = "PROJECT_TASK_THREAD_NOT_FOUND"
    PROJECT_TASK_STATUS_INVALID = "PROJECT_TASK_STATUS_INVALID"
    PROJECT_TASK_TAG_INVALID = "PROJECT_TASK_TAG_INVALID"
    PROJECT_TASK_DATE_INVALID = "PROJECT_TASK_DATE_INVALID"
    PROJECT_TASK_DISPATCH_INVALID = "PROJECT_TASK_DISPATCH_INVALID"
    PROJECT_CUSTOM_FIELD_NOT_FOUND = "PROJECT_CUSTOM_FIELD_NOT_FOUND"
    PROJECT_CUSTOM_FIELD_INVALID = "PROJECT_CUSTOM_FIELD_INVALID"
    PROJECT_CUSTOM_FIELD_VALUE_INVALID = "PROJECT_CUSTOM_FIELD_VALUE_INVALID"
    PROJECT_ATTACHMENT_INVALID = "PROJECT_ATTACHMENT_INVALID"
    PROJECT_KB_FORBIDDEN = "PROJECT_KB_FORBIDDEN"
    PROJECT_TASK_PARENT_INVALID = "PROJECT_TASK_PARENT_INVALID"
    PROJECT_COMMENT_CONCLUDED = "PROJECT_COMMENT_CONCLUDED"
    PROJECT_NODE_NOT_FOUND = "PROJECT_NODE_NOT_FOUND"
    PROJECT_NODE_NOT_CONFIRMED = "PROJECT_NODE_NOT_CONFIRMED"
    PROJECT_KB_BIND_FAILED = "PROJECT_KB_BIND_FAILED"
    PROJECT_CONNECTOR_INVALID = "PROJECT_CONNECTOR_INVALID"
    PROJECT_SKILL_INVALID = "PROJECT_SKILL_INVALID"
    PROJECT_CRON_INVALID = "PROJECT_CRON_INVALID"
    PROJECT_INSTRUCTION_INVALID = "PROJECT_INSTRUCTION_INVALID"


_DEFAULT_STATUS: dict[ErrorCode, int] = {
    ErrorCode.AUTH_FAILED: 401,
    ErrorCode.TOKEN_EXPIRED: 401,
    ErrorCode.SETUP_REQUIRED: 409,
    ErrorCode.DATABASE_NOT_EMPTY: 409,
    ErrorCode.BACKUP_DRIVER_MISMATCH: 400,
    ErrorCode.BACKUP_SCHEMA_INCOMPATIBLE: 400,
    ErrorCode.BACKUP_IN_PROGRESS: 409,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.USER_DISABLED: 403,
    ErrorCode.LOGIN_LOCKED: 429,
    ErrorCode.USERNAME_TAKEN: 409,
    ErrorCode.EMAIL_TAKEN: 409,
    ErrorCode.EMAIL_INVALID: 400,
    ErrorCode.PASSWORD_SAME_AS_OLD: 400,
    ErrorCode.PASSWORD_TOO_WEAK: 400,
    ErrorCode.SETUP_PASSWORD_WRONG: 401,
    ErrorCode.SETUP_RATE_LIMITED: 429,
    ErrorCode.SETUP_TOKEN_INVALID: 401,
    ErrorCode.AGENT_NOT_FOUND: 404,
    ErrorCode.AGENT_NOT_RUNNING: 409,
    ErrorCode.AGENT_FAILED: 500,
    ErrorCode.AGENT_BUSY: 409,
    ErrorCode.AGENT_NAME_TAKEN: 409,
    ErrorCode.AGENT_ID_INVALID: 400,
    ErrorCode.AGENT_ID_TAKEN: 409,
    ErrorCode.PROVIDER_NAME_TAKEN: 409,
    ErrorCode.PROVIDER_NOT_VISIBLE: 400,
    ErrorCode.PROVIDER_REFERENCED: 409,
    ErrorCode.PROVIDER_LOCAL_PROTECTED: 409,
    ErrorCode.CODEX_OAUTH_START_FAILED: 502,
    ErrorCode.STORAGE_BACKEND_NAME_TAKEN: 409,
    ErrorCode.STORAGE_BACKEND_REFERENCED: 409,
    ErrorCode.STORAGE_BACKEND_DEPS_FAILED: 503,
    ErrorCode.CHANNEL_KIND_UNSUPPORTED: 400,
    ErrorCode.CHANNEL_INVALID_CREDENTIALS: 400,
    ErrorCode.CHANNEL_NAME_TAKEN: 409,
    ErrorCode.CONNECTOR_NOT_FOUND: 404,
    ErrorCode.CONNECTOR_NAME_TAKEN: 409,
    ErrorCode.CONNECTOR_INVALID_CREDENTIALS: 400,
    ErrorCode.CONNECTOR_OAUTH_HTTPS_REQUIRED: 400,
    ErrorCode.CONNECTOR_MCP_URL_INVALID: 400,
    ErrorCode.CONNECTOR_MCP_HTTPS_REQUIRED: 400,
    ErrorCode.CONNECTOR_KIND_UNSUPPORTED: 400,
    ErrorCode.CONNECTOR_NOT_BOUND: 400,
    ErrorCode.CONNECTOR_ALREADY_BOUND: 409,
    ErrorCode.CONNECTOR_MCP_LOAD_FAILED: 502,
    ErrorCode.BRIDGE_NOT_FOUND: 404,
    ErrorCode.BRIDGE_AUTH_FAILED: 401,
    ErrorCode.BRIDGE_PEER_UNREACHABLE: 502,
    ErrorCode.BRIDGE_NOT_CONNECTED: 503,
    ErrorCode.BRIDGE_TUNNEL_FAILED: 502,
    ErrorCode.BRIDGE_REMOTE_UNSUPPORTED: 403,
    ErrorCode.BRIDGE_DISPLAY_NAME_TAKEN: 409,
    ErrorCode.BRIDGE_INBOUND_PASSIVE: 400,
    ErrorCode.CRON_TRIGGER_INVALID: 400,
    ErrorCode.SLASH_UNKNOWN: 400,
    ErrorCode.SLASH_BAD_ARGS: 400,
    ErrorCode.ATTACHMENT_UNSUPPORTED_TYPE: 400,
    ErrorCode.ATTACHMENT_TOO_LARGE: 413,
    ErrorCode.VOICE_BROWSER_ONLY: 422,
    ErrorCode.VOICE_KIND_UNSUPPORTED: 400,
    ErrorCode.VOICE_CAPABILITY_MISMATCH: 400,
    ErrorCode.VOICE_PROVIDER_DISABLED: 400,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.TLS_NOT_ELIGIBLE: 403,
    ErrorCode.TLS_ISSUE_IN_PROGRESS: 409,
    ErrorCode.TLS_DOMAIN_MISMATCH: 400,
    ErrorCode.WORKSPACE_OP_UNSUPPORTED: 400,
    ErrorCode.SKILL_IMPORT_UNSUPPORTED_URL: 400,
    ErrorCode.SKILL_IMPORT_FAILED: 502,
    ErrorCode.SKILL_ALREADY_EXISTS: 409,
    ErrorCode.SKILL_PACKAGE_NOT_FOUND: 404,
    ErrorCode.SKILL_PACKAGE_NAME_TAKEN: 409,
    ErrorCode.SKILL_PACKAGE_BACKEND_UNSUPPORTED: 400,
    ErrorCode.ACP_BACKEND_UNSUPPORTED: 400,
    ErrorCode.PUBLISHED_EXPERT_SLUG_TAKEN: 409,
    ErrorCode.PUBLISHED_EXPERT_ALREADY_EXISTS: 409,
    ErrorCode.OIDC_BAD_REQUEST: 400,
    ErrorCode.SSO_IDENTITY_TAKEN: 409,
    ErrorCode.SSO_UNBIND_REQUIRES_PASSWORD: 400,
    ErrorCode.EXPERT_MARKET_FAILED: 502,
    ErrorCode.SKILLHUB_SSL_FAILED: 502,
    ErrorCode.DESKTOP_SESSION_LIMIT: 429,
    ErrorCode.DESKTOP_CAPTURE_FAILED: 503,
    ErrorCode.PLUGIN_INVALID_ARCHIVE: 400,
    ErrorCode.PLUGIN_INSTALL_FAILED: 502,
    ErrorCode.PLUGIN_ALREADY_EXISTS: 409,
    ErrorCode.KNOWLEDGE_FEATURE_DISABLED: 403,
    ErrorCode.KNOWLEDGE_PREREQUISITES_FAILED: 409,
    ErrorCode.KNOWLEDGE_NOT_FOUND: 404,
    ErrorCode.KNOWLEDGE_FORBIDDEN: 403,
    ErrorCode.KNOWLEDGE_DOC_LIMIT: 409,
    ErrorCode.KNOWLEDGE_DOC_TOO_LARGE: 413,
    ErrorCode.KNOWLEDGE_BASE_LIMIT: 409,
    ErrorCode.KNOWLEDGE_UNSUPPORTED_TYPE: 400,
    ErrorCode.KNOWLEDGE_NAME_TAKEN: 409,
    ErrorCode.KNOWLEDGE_NAME_INVALID: 400,
    ErrorCode.AVATAR_INVALID: 400,
    ErrorCode.AVATAR_TOO_LARGE: 413,
    ErrorCode.INVITE_INVALID: 400,
    ErrorCode.INVITE_ROLE_MISSING: 409,
    ErrorCode.USER_ROLE_IN_USE: 409,
    ErrorCode.INVITE_USED: 409,
    ErrorCode.INVITE_EXPIRED: 410,
    ErrorCode.INVITE_REVOKED: 410,
    ErrorCode.INVITE_RATE_LIMITED: 429,
    ErrorCode.WORKSPACE_ROOT_RESTRICTED: 400,
    ErrorCode.WORKSPACE_ROOT_CONTAINER_UNSUPPORTED: 400,
    ErrorCode.TOKEN_QUOTA_EXCEEDED: 403,
    ErrorCode.AGENT_QUOTA_EXCEEDED: 403,
    ErrorCode.CAPTCHA_REQUIRED: 400,
    ErrorCode.CAPTCHA_FAILED: 400,
    ErrorCode.CONFIG_FILE_CORRUPT: 400,
    ErrorCode.TEAM_NOT_FOUND: 404,
    ErrorCode.TEAM_MEMBERS_TOO_FEW: 400,
    ErrorCode.TEAM_MEMBER_INVALID: 400,
    ErrorCode.TEAM_MEMBER_BUSY: 409,
    ErrorCode.TEAM_NOT_SHAREABLE: 400,
    ErrorCode.TEAM_RUN_NOT_FOUND: 404,
    ErrorCode.TEAM_RUN_PHASE_INVALID: 409,
    ErrorCode.TEAM_PHASE_GATE_FAILED: 409,
    ErrorCode.TEAM_DECISION_PENDING: 409,
    ErrorCode.TEAM_DECISION_NOT_PENDING: 409,
    ErrorCode.TEAM_DECISION_OPTION_INVALID: 400,
    ErrorCode.TEAM_SPEC_BOUNDARY_EMPTY: 409,
    ErrorCode.TEAM_TASK_DEPS_UNMET: 409,
    ErrorCode.TEAM_TASK_GRAPH_INVALID: 409,
    ErrorCode.TEAM_REWORK_LOOP_LIMIT: 409,
    ErrorCode.TEAM_FINDING_REOPENED: 409,
    ErrorCode.TEAM_ATTEMPT_STALE: 409,
    ErrorCode.TEAM_SCOPE_VIOLATION: 409,
    ErrorCode.TEAM_VERDICT_FINDINGS_REQUIRED: 409,
    ErrorCode.TEAM_REVIEW_SELF_AUDIT: 409,
    ErrorCode.TEAM_ARTIFACT_STALE: 409,
    ErrorCode.TEAM_ARTIFACT_OWNERSHIP_DENIED: 409,
    ErrorCode.TEAM_RUN_MEMBER_LIMIT: 409,
    ErrorCode.TEAM_RUN_TASK_LIMIT: 409,
    # 空花名册 = 422（请求合法但该 run 无法规划）；与 TEAM_RUN_MEMBER_LIMIT(409, 上限) 方向相反，零重叠。
    ErrorCode.TEAM_RUN_ROSTER_EMPTY: 422,
    # Plan gate (T2): 草稿非法 = 422（不可处理实体），无草稿可批/可丢 = 409（状态冲突）。
    ErrorCode.TEAM_PLAN_DRAFT_INVALID: 422,
    ErrorCode.TEAM_PLAN_DRAFT_MISSING: 409,
    ErrorCode.TEAM_TIER_INVALID: 400,
    ErrorCode.TEAM_ROLE_UNKNOWN: 400,
    ErrorCode.TEAM_TIER_DOWNGRADE_FORBIDDEN: 400,
    ErrorCode.TEAM_RUN_CONFLICT: 409,
    ErrorCode.TEAM_TASK_CLAIM_CONFLICT: 409,
    ErrorCode.TEAM_PHASE_CONFLICT: 409,
    ErrorCode.TEAM_CROSS_RUN_REFERENCE: 403,
    ErrorCode.TEAM_RUN_TERMINAL: 409,
    ErrorCode.TEAM_TASK_TERMINAL: 409,
    ErrorCode.TEAM_TASK_STATUS_INVALID: 409,
    ErrorCode.TEAM_MEMBER_NOT_IN_RUN: 403,
    ErrorCode.TEAM_ARTIFACT_INVALID: 400,
    ErrorCode.TEAM_ARTIFACT_PATH_INVALID: 400,
    ErrorCode.TEAM_RUN_GOAL_EMPTY: 400,
    ErrorCode.TEAM_RUN_GOAL_TOO_LONG: 400,
    ErrorCode.TEAM_COMMAND_UNKNOWN: 400,
    ErrorCode.TEAM_EFFORT_INVALID: 400,
    ErrorCode.PROJECT_NOT_FOUND: 404,
    ErrorCode.PROJECT_FORBIDDEN: 403,
    ErrorCode.PROJECT_ROLE_FORBIDDEN: 403,
    ErrorCode.PROJECT_MEMBER_INVALID: 400,
    ErrorCode.PROJECT_STATUS_INVALID: 409,
    ErrorCode.PROJECT_TASK_NOT_FOUND: 404,
    ErrorCode.PROJECT_TASK_THREAD_NOT_FOUND: 404,
    ErrorCode.PROJECT_TASK_STATUS_INVALID: 409,
    ErrorCode.PROJECT_TASK_TAG_INVALID: 409,
    ErrorCode.PROJECT_TASK_DATE_INVALID: 400,
    ErrorCode.PROJECT_TASK_DISPATCH_INVALID: 409,
    ErrorCode.PROJECT_CUSTOM_FIELD_NOT_FOUND: 404,
    ErrorCode.PROJECT_CUSTOM_FIELD_INVALID: 409,
    ErrorCode.PROJECT_CUSTOM_FIELD_VALUE_INVALID: 400,
    ErrorCode.PROJECT_ATTACHMENT_INVALID: 400,
    ErrorCode.PROJECT_KB_FORBIDDEN: 403,
    ErrorCode.PROJECT_TASK_PARENT_INVALID: 400,
    ErrorCode.PROJECT_COMMENT_CONCLUDED: 409,
    ErrorCode.PROJECT_NODE_NOT_FOUND: 404,
    ErrorCode.PROJECT_NODE_NOT_CONFIRMED: 409,
    ErrorCode.PROJECT_KB_BIND_FAILED: 500,
    # An unknown/unavailable connector kind is a caller error (400); the
    # duplicate-declaration branch passes ``status=409`` explicitly.
    ErrorCode.PROJECT_CONNECTOR_INVALID: 400,
    ErrorCode.PROJECT_SKILL_INVALID: 409,
    ErrorCode.PROJECT_CRON_INVALID: 409,
    ErrorCode.PROJECT_INSTRUCTION_INVALID: 400,
}


@dataclass
class OctopError(Exception):
    code: ErrorCode
    message: str
    status: int = 0
    details: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.status == 0:
            self.status = _DEFAULT_STATUS[self.code]
        super().__init__(self.message)

    def interpolation_kwargs(self, **kwargs: object) -> dict[str, object]:
        """``details`` minus the keys that name ``error_message``'s own parameters.

        ``error_message(code, locale, **kwargs)`` takes the code positionally, so a
        ``details["code"]`` -- which G6's graph refusal carries on purpose, it is part
        of that error's contract -- collided with the parameter and raised
        ``TypeError`` **at serialization time**: the refusal existed but could never
        reach a client. The reserved names are derived from the function's signature
        instead of being hard-coded, so a future parameter is covered automatically.

        The keys are **not** dropped from the envelope -- only from message
        interpolation -- so ``detail.code`` still reaches the caller.

        Deliberately **no** ``except TypeError`` around the interpolation: a broad
        except here would swallow genuine failures and turn a crash into a silently
        wrong message. This fixes the *class* "interpolation argument mismatch", not
        one code's symptom.
        """
        merged = {**self.details, **kwargs}
        return {key: value for key, value in merged.items() if key not in _ERROR_MESSAGE_PARAMS}

    def localized_message(self, locale: str | Locale, **kwargs: object) -> str:
        loc = normalize_locale(str(locale))
        try:
            return i18n_error_message(self.code.value, loc, **self.interpolation_kwargs(**kwargs))
        except KeyError:
            return self.message

    @classmethod
    def localized(
        cls,
        code: ErrorCode,
        locale: str | Locale = "en",
        *,
        message: str | None = None,
        status: int = 0,
        details: dict[str, Any] | None = None,
        **kwargs: object,
    ) -> OctopError:
        msg = (
            message
            if message is not None
            else i18n_error_message(code.value, normalize_locale(str(locale)), **kwargs)
        )
        return cls(code, msg, status=status, details=details or {})

    def to_envelope(self, *, locale: str | Locale | None = None) -> dict[str, Any]:
        message = self.localized_message(locale) if locale is not None else self.message
        return {
            "error": {
                "code": self.code.value,
                "message": message,
                "details": self.details,
            }
        }


def corrupt_config_error(path: object, detail: str) -> OctopError:
    """``OctopError`` for a config file that exists but cannot be parsed.

    Raised instead of writing back a merged-into-empty dict, which would destroy
    every unrelated setting (issue #730). Carries the path and the parser
    position only — never file contents, which hold database credentials.
    """
    return OctopError(
        ErrorCode.CONFIG_FILE_CORRUPT,
        f"{path} is not valid JSON ({detail}); fix it and retry — no settings were changed",
        details={"path": str(path), "detail": detail},
    )
