-- Schema v19: Octop↔Octop bridge connections (per-user remote links).

CREATE TABLE IF NOT EXISTS bridge_connections (
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id           TEXT NOT NULL UNIQUE,
  owner_user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  peer_base_url           TEXT NOT NULL,
  peer_username           TEXT NOT NULL,
  display_name            TEXT NOT NULL,
  notes                   TEXT,
  icon_name               TEXT,
  credential_blob         BYTEA,
  access_token_blob       BYTEA,
  token_expires_at        INTEGER,
  status                  TEXT NOT NULL DEFAULT 'disconnected',
  last_error              TEXT,
  last_seen_at            INTEGER,
  auto_reconnect          INTEGER NOT NULL DEFAULT 1,
  created_at              INTEGER NOT NULL,
  updated_at              INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bridge_connections_owner
  ON bridge_connections(owner_user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bridge_connections_owner_display
  ON bridge_connections(owner_user_id, display_name);

UPDATE _schema_version SET version = 19;
