-- Schema v22: project configuration (connector kinds, skill projections, instruction,
-- cron ownership).
--
-- Canonical v21 -> v22 DDL for PostgreSQL. Executed statement-by-statement by
-- ``_apply_postgresql_migration`` (split on ";\n"), so every statement must be
-- self-contained. ``IF NOT EXISTS`` guards keep a re-run safe; ``migrate.py``
-- gains no ``_ensure_*`` helper for this version.
--
-- Exactly the seven DDL items frozen in PLAN.md §10.1: two declaration tables
-- (each with its read-path index), two columns, and one index for the cron list
-- path. ``project_connectors`` stores the connector **kind only** -- never an
-- instance id or credential (R17).
--
-- Timestamp columns are INTEGER unix seconds, matching 001_initial.pg.sql.

CREATE TABLE IF NOT EXISTS project_connectors (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
  kind       TEXT NOT NULL,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at INTEGER NOT NULL,
  UNIQUE(project_id, kind)
);
CREATE INDEX IF NOT EXISTS idx_project_connectors_project ON project_connectors(project_id, kind);

CREATE TABLE IF NOT EXISTS project_skills (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
  agent_id   TEXT NOT NULL,
  skill_slug TEXT NOT NULL,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at INTEGER NOT NULL,
  UNIQUE(project_id, agent_id, skill_slug)
);
CREATE INDEX IF NOT EXISTS idx_project_skills_project ON project_skills(project_id, agent_id);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS instruction TEXT NOT NULL DEFAULT '';

ALTER TABLE cron_jobs ADD COLUMN IF NOT EXISTS project_id TEXT;
CREATE INDEX IF NOT EXISTS idx_cron_jobs_project ON cron_jobs(project_id);

UPDATE _schema_version SET version = 22;
